name: Build Firmware

on:
  workflow_call:
    outputs:
      version:
        description: "The version from the tag"
        value: ${{ jobs.build.outputs.version }}
      changelog:
        description: "The changelog for the current version"
        value: ${{ jobs.build.outputs.changelog }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
      changelog: ${{ steps.changelog.outputs.CHANGES }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    
    - name: Build Firmware
      run: |
        pio run -t buildfs  # Build SPIFFS
        pio run            # Build firmware
        
    - name: Install esptool
      run: |
        pip install esptool
        
    - name: Merge firmware and SPIFFS
      run: |
        esptool.py --chip esp32 merge_bin \
          --flash_mode dio \
          --flash_freq 40m \
          --flash_size 4MB \
          -o .pio/build/esp32dev/filaman_full.bin \
          0x1000 .pio/build/esp32dev/bootloader.bin \
          0x8000 .pio/build/esp32dev/partitions.bin \
          0x10000 .pio/build/esp32dev/firmware.bin \
          0x290000 .pio/build/esp32dev/spiffs.bin

    - name: Prepare OTA firmware
      run: |
        cp .pio/build/esp32dev/firmware.bin .pio/build/esp32dev/filaman_ota.bin
    
    - name: Get version from tag
      id: get_version
      run: |
        if [ -n "$GITEA_REF" ]; then
          echo "VERSION=${GITEA_REF#refs/tags/v}" >> $GITEA_OUTPUT
        else
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        fi
      
    - name: Read CHANGELOG.md
      id: changelog
      run: |
        VERSION=${{ steps.get_version.outputs.VERSION }}
        CHANGELOG=$(awk "/## \\[$VERSION\\]/{p=1;print;next} /## \\[/{p=0} p" CHANGELOG.md)
        if [ -n "$GITEA_OUTPUT" ]; then
          echo "CHANGES<<EOF" >> $GITEA_OUTPUT
          echo "$CHANGELOG" >> $GITEA_OUTPUT
          echo "EOF" >> $GITEA_OUTPUT
        else
          echo "CHANGES<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: |
          .pio/build/esp32dev/filaman_full.bin
          .pio/build/esp32dev/filaman_ota.bin