name: Gitea Release

on:
  workflow_call:
    inputs:
      gitea_ref_name:
        required: true
        type: string
      gitea_server_url:
        required: true
        type: string
      gitea_repository:
        required: true
        type: string
    secrets:
      GITEA_TOKEN:
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    
    - name: Build Firmware
      run: |
        pio run -t buildfs  # Build SPIFFS
        pio run            # Build firmware
        
    - name: Install esptool
      run: |
        pip install esptool
        
    - name: Merge firmware and SPIFFS
      run: |
        esptool.py --chip esp32 merge_bin \
          --flash_mode dio \
          --flash_freq 40m \
          --flash_size 4MB \
          -o .pio/build/esp32dev/filaman_full.bin \
          0x1000 .pio/build/esp32dev/bootloader.bin \
          0x8000 .pio/build/esp32dev/partitions.bin \
          0x10000 .pio/build/esp32dev/firmware.bin \
          0x3D0000 .pio/build/esp32dev/spiffs.bin

    - name: Prepare OTA firmware
      run: |
        cp .pio/build/esp32dev/firmware.bin .pio/build/esp32dev/filaman_ota.bin
    
    - name: Create Release
      env:
        TOKEN: ${{ secrets.GITEA_TOKEN }}
      run: |
        TAG="${{ inputs.gitea_ref_name }}"
        API_URL="${{ inputs.gitea_server_url }}/api/v1"
        REPO="${{ inputs.gitea_repository }}"
        
        # Create release
        RESPONSE=$(curl -k -s \
          -X POST \
          -H "Authorization: token ${TOKEN}" \
          -H "Content-Type: application/json" \
          -d "{
            \"tag_name\":\"${TAG}\",
            \"name\":\"Release ${TAG}\",
            \"body\":\"${{ steps.changelog.outputs.CHANGES }}\"
          }" \
          "${API_URL}/repos/${REPO}/releases")
        
        RELEASE_ID=$(echo "$RESPONSE" | grep -o '"id":[0-9]*' | cut -d':' -f2 | head -n1)
        
        if [ -n "$RELEASE_ID" ]; then
          echo "Release created with ID: $RELEASE_ID"
          
          # Upload binaries
          cd .pio/build/esp32dev
          for file in filaman_full.bin filaman_ota.bin; do
            echo "Uploading $file..."
            curl -k -s \
              -X POST \
              -H "Authorization: token ${TOKEN}" \
              -H "Content-Type: application/octet-stream" \
              --data-binary "@$file" \
              "${API_URL}/repos/${REPO}/releases/${RELEASE_ID}/assets?name=$file"
          done
        else
          echo "Failed to create release. Response:"
          echo "$RESPONSE"
          exit 1
        fi