name: Gitea Release

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      changelog:
        type: string
        required: true

jobs:
  release:
    runs-on: gitea-runner
    steps:
      - name: Debug Info
        run: |
          echo "Version: ${{ inputs.version }}"
          echo "Changelog: ${{ inputs.changelog }}"
          echo "Tag: ${GITHUB_REF#refs/tags/}"
          
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio esptool
      
      - name: Build
        run: |
          pio run -t buildfs
          pio run
          
      - name: Create full firmware
        run: |
          esptool.py --chip esp32 merge_bin \
            --flash_mode dio \
            --flash_freq 40m \
            --flash_size 4MB \
            -o .pio/build/esp32dev/filaman_full.bin \
            0x1000 .pio/build/esp32dev/bootloader.bin \
            0x8000 .pio/build/esp32dev/partitions.bin \
            0x10000 .pio/build/esp32dev/firmware.bin \
            0x290000 .pio/build/esp32dev/spiffs.bin
          cp .pio/build/esp32dev/firmware.bin .pio/build/esp32dev/filaman_ota.bin
      
      - name: Create Release
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          curl -X POST "${GITEA_API_URL}/repos/${GITEA_REPOSITORY}/releases" \
            -H "Authorization: token ${GITEA_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\":\"$TAG\",\"name\":\"Release ${{ inputs.version }}\",\"body\":\"${{ inputs.changelog }}\",\"draft\":false,\"prerelease\":false}"
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          GITEA_API_URL: ${{ secrets.GITEA_API_URL }}
          GITEA_REPOSITORY: ${{ secrets.GITEA_REPOSITORY }}