name: Gitea Release

on:
  workflow_call:
    inputs:
      gitea_ref_name:
        required: true
        type: string
      gitea_server_url:
        required: true
        type: string
      gitea_repository:
        required: true
        type: string
    secrets:
      GITEA_TOKEN:
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio esptool
    
    - name: Build Firmware
      run: |
        pio run -e esp32dev_ota -t buildfs  # Build SPIFFS
        pio run -e esp32dev_ota            # Build firmware
        cp .pio/build/esp32dev_ota/firmware.bin .pio/build/esp32dev_ota/filaman.bin
        cp .pio/build/esp32dev_ota/spiffs.bin .pio/build/esp32dev_ota/filaman_spiffs.bin
        
    - name: Prepare binaries
      run: |
        cd .pio/build/esp32dev_ota
        
        # Create OTA binary (firmware only)
        cp firmware.bin filaman_ota.bin
        
        # Use esptool to create the full binary
        esptool.py --chip esp32 merge_bin \
          --flash_mode dio \
          --flash_freq 40m \
          --flash_size 4MB \
          --target-offset 0x0 \
          -o filaman_full.bin \
          0x1000 bootloader.bin \
          0x8000 partitions.bin \
          0x10000 firmware.bin \
          0x3D0000 spiffs.bin
        
        # Verify binaries
        echo "File sizes:"
        ls -lh *.bin
        
        echo "Binary information:"
        echo "OTA binary info:"
        esptool.py --chip esp32 image_info filaman_ota.bin || true
        echo "Full binary first 64 bytes:"
        od -A x -t x1z -N 64 filaman_full.bin

    - name: Create Release
      env:
        TOKEN: ${{ secrets.GITEA_TOKEN }}
      run: |
        TAG="${{ inputs.gitea_ref_name }}"
        API_URL="${{ inputs.gitea_server_url }}/api/v1"
        REPO="${{ inputs.gitea_repository }}"
        
        # Create release
        RESPONSE=$(curl -k -s \
          -X POST \
          -H "Authorization: token ${TOKEN}" \
          -H "Content-Type: application/json" \
          -d "{
            \"tag_name\":\"${TAG}\",
            \"name\":\"Release ${TAG}\",
            \"body\":\"${{ steps.changelog.outputs.CHANGES }}\"
          }" \
          "${API_URL}/repos/${REPO}/releases")
        
        RELEASE_ID=$(echo "$RESPONSE" | grep -o '"id":[0-9]*' | cut -d':' -f2 | head -n1)
        
        if [ -n "$RELEASE_ID" ]; then
          echo "Release created with ID: $RELEASE_ID"
          
          # Upload binaries
          cd .pio/build/esp32dev_ota
          for file in filaman_full.bin filaman_ota.bin filaman.bin filaman_spiffs.bin; do
            echo "Uploading $file..."
            curl -k -s \
              -X POST \
              -H "Authorization: token ${TOKEN}" \
              -H "Content-Type: application/octet-stream" \
              --data-binary "@$file" \
              "${API_URL}/repos/${REPO}/releases/${RELEASE_ID}/assets?name=$file"
          done
        else
          echo "Failed to create release. Response:"
          echo "$RESPONSE"
          exit 1
        fi