name: GitHub Release

on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/providers/build.yml

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: firmware
        path: firmware

    - name: Create GitHub Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create "${{ github.ref_name }}" \
          --title "Release ${{ needs.build.outputs.version }}" \
          --notes "${{ needs.build.outputs.changelog }}" \
          firmware/filaman_full.bin \
          firmware/filaman_ota.bin