name: GitHub Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      changelog:
        required: true
        type: string

permissions:
  contents: write      # Required for creating releases
  issues: read        # Required for reading changelog
  pull-requests: read # Required for reading changelog

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating releases at job level
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio esptool
    
    - name: Build Firmware
      run: |
        pio run -t buildfs  # Build SPIFFS
        pio run            # Build firmware
        
    - name: Merge firmware and SPIFFS
      run: |
        esptool.py --chip esp32 merge_bin \
          --flash_mode dio \
          --flash_freq 40m \
          --flash_size 4MB \
          -o .pio/build/esp32dev/filaman_full.bin \
          0x1000 .pio/build/esp32dev/bootloader.bin \
          0x8000 .pio/build/esp32dev/partitions.bin \
          0x10000 .pio/build/esp32dev/firmware.bin \
          0x290000 .pio/build/esp32dev/spiffs.bin

    - name: Prepare OTA firmware
      run: cp .pio/build/esp32dev/firmware.bin .pio/build/esp32dev/filaman_ota.bin
    
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${{ github.ref_name }}" \
          --title "Release ${{ inputs.version }}" \
          --notes "${{ inputs.changelog }}" \
          ".pio/build/esp32dev/filaman_full.bin#filaman_full.bin" \
          ".pio/build/esp32dev/filaman_ota.bin#filaman_ota.bin"