name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  prepare:
    runs-on: gitea-runner
    outputs:
      version: ${{ steps.version.outputs.version }}
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Get version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Get changelog
        id: changelog
        run: |
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Run GitHub Release
        if: github.server_url == 'https://github.com'
        uses: ./.github/workflows/providers/github-release.yml
        with:
          version: ${{ steps.version.outputs.version }}
          changelog: ${{ steps.changelog.outputs.changelog }}
        
      - name: Run Gitea Release
        if: github.server_url != 'https://github.com'
        uses: ./.github/workflows/providers/gitea-release.yml
        with:
          version: ${{ steps.version.outputs.version }}
          changelog: ${{ steps.changelog.outputs.changelog }}