name: Release Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  route:
    runs-on: ubuntu-latest
    outputs:
      provider: ${{ steps.provider.outputs.provider }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine CI Provider
        id: provider
        run: |
          if [[ "$GITHUB_ACTIONS" == "true" ]]; then
            echo "provider=github" >> $GITHUB_OUTPUT
          elif [[ "$GITEA_ACTIONS" == "true" ]]; then
            echo "provider=gitea" >> $GITHUB_OUTPUT
          else
            echo "provider=unknown" >> $GITHUB_OUTPUT
          fi

  github-release:
    needs: route
    if: needs.route.outputs.provider == 'github'
    uses: ./.github/workflows/providers/github-release.yml

  gitea-release:
    needs: route
    if: needs.route.outputs.provider == 'gitea'
    uses: ./.github/workflows/providers/gitea-release.yml